### ISSUE TITLE
Support formatting numbers in scientific notation

### ISSUE THREAD

**Issue by gorfist** [ArzDigitalLabs/reduce-precision#2]
The reduce-precision package currently does not support formatting numbers provided in scientific notation, such as 4.4846674098720425e-14. When attempting to format numbers in this notation, the package may produce incorrect results like 0 result.

To enhance the package's functionality and make it more versatile, it would be beneficial to add support for handling numbers in scientific notation. This would allow users to format a wider range of numbers accurately, especially very small or very large values.

Thank you for considering this feature request.

**Comment by mohammadanaraki** [comment]
Thank you for pointing this out! Support for formatting numbers in scientific notation has been added. You can check out the [0278a0f](https://github.com/ArzDigitalLabs/reduce-precision/commit/0278a0f6792dd2c97fcddc0526ff7659e4d1cd6b) here.
