### ISSUE TITLE
Add support for customizable separator and decimal signs

### ISSUE THREAD

**Issue by gorfist** [ArzDigitalLabs/reduce-precision#3]
Currently, the `reduce-precision` package uses fixed characters for the thousand separator (`,`) and decimal point (`.`) when formatting numbers in English. However, different applications and user preferences may require alternative characters for these separators.

To enhance the flexibility and adaptability of the package, I suggest adding options to customize the separator and decimal signs. This would allow users to specify their preferred characters for separating thousands and representing decimal points.

For example, some applications may prefer to use a thin space (`' '`) as the thousand separator. Customizable options would enable users to easily configure the package to match their specific needs.

Please consider implementing this feature to make the `reduce-precision` package more versatile and user-friendly.

Thank you for your consideration.

**Comment by mohammadanaraki** [comment]
Thank you for your suggestion. I'm pleased to inform you that we have implemented this feature as per your recommendation.

### **Implemented Feature:**

We have introduced a setLanguage option with the following keys:

    thousandSeparator
    decimalSeparator

How to Use:

Users can now specify their preferred characters for these separators when formatting numbers in English. Here's a quick example of how to use these options:

How to Use:

Users can now specify their preferred characters for these separators when formatting numbers in English. Here's a quick example of how to use these options:

```javascript
formatter.setLanguage('en', {
  thousandSeparator: ',',
  decimalSeparator: '.'
});
```
