### ISSUE TITLE
return 0 for numbers in range 0.1 to 0.00001

### ISSUE THREAD

**Issue by MiladRST** [ArzDigitalLabs/reduce-precision#4]
It seems the format function can not handle the numbers between 0.1 to 0.00001.

**Comment by mohammadanaraki** [comment]
Thank you for the clarification. I understand now that the issue wasn't related to errors occurring within the specified range, but rather incorrect output being produced.

In version 0.0.3, we've implemented a fix to ensure that the format function generates the correct output.
