### ISSUE TITLE
Add support for auto precision in 'number' template

### ISSUE THREAD

**Issue by gorfist** [ArzDigitalLabs/reduce-precision#6]
The 'auto' precision option is not working as expected when using the 'number' template. It would be great if the 'number' template could support the 'auto' precision mode similar to how it works with the 'usd' template, just without the '$' sign. This would provide more flexibility and consistency in number formatting across different templates.

**Comment by mohammadanaraki** [comment]
We've fixed the 'auto' precision in the 'number' template in v1.3
