### ISSUE TITLE
Add Browser Compatibility

### ISSUE THREAD

**Issue by MhKh78** [ArzDigitalLabs/reduce-precision#9]
Current building process only provides built Js files that are compatible with NodeJS module system (CommonJs),
In order for the code to be browser compatible there needs to be a build pipeline for bundling the files  (preferably webpack bundle) into a single Js file (which is better to be then uglified and minified)
the output should be something like
/lib/*.min.js
or
/dist/*/min.js
so the script can be easily loaded with html script tag

**Comment by mohammadanaraki** [comment]
Browser support added in version 1.3


```html
<script src="https://cdn.jsdelivr.net/npm/reduce-precision/lib/bundle.min.js"></script>
```
